apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: appconf-etcd-operator
rules:
- apiGroups:
  - etcd.database.coreos.com
  resources:
  - etcdclusters
  - etcdbackups
  - etcdrestores
  verbs:
  - "*"
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - "*"
- apiGroups:
  - ""
  resources:
  - pods
  - services
  - endpoints
  - persistentvolumeclaims
  - events
  verbs:
  - "*"
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - "*"
# The following permissions can be removed if not using S3 backup and TLS
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: appconf-etcd-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: appconf-etcd-operator
subjects:
- kind: ServiceAccount
  name: default
  namespace: kube-system
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: appconf-etcd-operator
  namespace: kube-system
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: appconf-etcd-operator
    spec:
      containers:
      - name: appconf-etcd-operator
        image: quay.io/coreos/etcd-operator:v0.9.4
        command:
        - etcd-operator
        # Uncomment to act for resources in all namespaces. More information in doc/user/clusterwide.md
        #- -cluster-wide
        env:
        - name: MY_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kubesys-config
  namespace: kube-system
data:
  VM.properties: |
    GROUP=cloudplus.io
    VERSION=v1alpha3
    PLURAL=virtualmachines
    KIND=VirtualMachine
    CLASS=com.github.kubesys.kubernetes.api.model.VirtualMachineWatcher
  Disk.properties: |
    GROUP=cloudplus.io
    VERSION=v1alpha3
    PLURAL=virtualmachinedisks
    KIND=VirtualMachineDisk
    CLASS=com.github.kubesys.kubernetes.api.model.VirtualMachineDiskWatcher
